### ISSUE TITLE
Adding .js leaflet plugin

### ISSUE THREAD

**Issue by matijamatija** [bluehalo/ngx-leaflet#101]
I'm trying to add a .js plugin called Leaflet TimeDimension: https://github.com/socib/Leaflet.TimeDimension 

Unfortunately I'm not able to add it. I did the following. Added this in .angular-cli.json:
```
      "scripts": [
        "./assets/iso8601.min.js",
        "./assets/leaflet.timedimension.min.js"
      ],
```

In tsconfig.json I've added `"allowJs": true,`

In typings.d.ts:
```
declare var TimeDimension:any;
declare var L:any;
declare var iso8601:any;
```

But in console I get the following error.

```
Uncaught ReferenceError: L is not defined
    at scripts.bundle.js:21
```

I'm guessing this is connected to order of how Angular CLI builds the files. Any Idea how to add plugins?

Btw. I've also tried both of those options in app.component.ts (not at the same time):

```
 import * as variable from 'TimeDimension';
 import * as TimeDimension from '../assets/leaflet.timedimension.min.js';
```

**Comment by reblace** [comment]
Bear with me cause this is a bit of a long explanation...

The issue you're running into is related to how Angular CLI uses Webpack and how Webpack managed scoped vs global modules. This is combined with the fact that leaflet.timedimension is modifying the globally exported leaflet variable 'L'. It's not impossible to get everything working, it's just a bit complicated and weird.

There are a few subtly different ways to get this working, but I'm gonna show you the way that I think makes the most sense. Which is to scope packages as best we can. Anyhow, follow these directions:

1. Start with a working @angular/cli project that has ngx-leaflet set up and installed - [tutorial](https://www.asymmetrik.com/ngx-leaflet-tutorial-angular-cli/), [github](https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli)
2. Install the new dependencies
   ```npm install --save leaflet-timedimension iso8601-js-period```
3. Modify .angular-cli.json to add the stylesheet and global js scripts. At a minimum, we need iso8601-js-period to be global because it is used by the Leaflet.TimeDimension library. 
   ```
   ...
      "styles": [
        "styles.css",
        "../node_modules/leaflet/dist/leaflet.css",
        "../node_modules/leaflet-timedimension/dist/leaflet.timedimension.control.css"
      ],
      "scripts": [
        "../node_modules/iso8601-js-period/iso8601.js"
      ],
   ...
   ```
4. Update typings.d.ts to open up leaflet.timedimension stuff to the leaflet module (this is a horrible type definition, but we're just trying to get this working):
   ```
   import * as L from 'leaflet';
   declare module 'leaflet' {
      var timeDimension: any;
   }
   ```
5. Component template. Just adding a layers binding so we can add the timeDimension layer:
   ```
   <div class="map"
           leaflet
           [leafletOptions]="options"
           [leafletLayers]="layers"></div>
   ```
6. Component class. By importing leaflet into 'L', and then doing a typeless import of the actual umd packaged bundle file for leaflet.timedimension, we should end up with a scoped L variable that has been extended by leaflet.timedimension:
   ```
   import { Component } from '@angular/core';
   import * as L from 'leaflet';
   import '../../node_modules/leaflet-timedimension/dist/leaflet.timedimension.src.js';

   @Component({
     selector: 'app-root',
     templateUrl: './app.component.html',
     styleUrls: ['./app.component.css']
   })
   export class AppComponent {

     options = {
       zoom: 7,
       center: L.latLng([ 45.3, 0.9 ]),
       timeDimension: true,
       timeDimensionControl: true
     };

     layerGrid = L.tileLayer.wms('https://ogcie.iblsoft.com/metocean/wms', {
       layers: 'foreground-lines',
       format: 'image/png',
       transparent: true,
       crs: L.CRS.EPSG4326
     });

     dataLayer = L.tileLayer.wms('https://ogcie.iblsoft.com/metocean/wms', {
       layers: 'gfs-temperature-isbl',
       format: 'image/png',
       opacity: 0.3,
       transparent: true,
       crs: L.CRS.EPSG4326,
       attribution: 'OGC MetOcean DWG Best Practice Example, IBL Software Engineering'
     });

     tdWmsLayer = L.timeDimension.layer.wms(this.dataLayer);
     layers = [
       L.tileLayer('http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}', {
         maxZoom: 20,
         subdomains: ['mt0', 'mt1', 'mt2', 'mt3'],
         detectRetina: true
       }),
       this.layerGrid,
       this.tdWmsLayer
     ];

   }
   ```

If all goes well, this should be a working example. I just uploaded a repo with this example. Let me know if you have any issues running it.

https://github.com/Asymmetrik/ngx-leaflet-tutorial-3rd-party-libs

**Comment by reblace** [comment]
I created this repo with the example above: https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli-leaflet.timedimension

If you have a working example, feel free to put in a PR.

**Comment by reblace** [comment]
The linked repo is a WIP, I'm renaming it and adding more examples for other libs:

https://github.com/Asymmetrik/ngx-leaflet-tutorial-3rd-party-lib-examples

**Comment by reblace** [comment]
Gonna close this since I haven't heard anything further. If you have issues with the tutorial, put in a ticket on that repo. Thanks!

**Comment by matijamatija** [comment]
Hey @reblace. Sorry I forgot to reply.
This was very useful and it worked. Thank you very much for the detailed explaination.

**Comment by tomer-liran** [comment]
Hi, I'm following this tutorial right now but still once adding everything I'm getting the error "Object literal may only specify known properties, and 'timeDimension' does not exist in type 'MapOptions'". 

Is this method surely still relevant?

**Comment by ShawnWon** [comment]
> Hi, I'm following this tutorial right now but still once adding everything I'm getting the error "Object literal may only specify known properties, and 'timeDimension' does not exist in type 'MapOptions'".
> 
> Is this method surely still relevant?

Hi, Tomerlir, I met the same error message as "timeDimension" does not exist in type 'MapOptions', did you find the solution on this?
