### ISSUE TITLE
leaflet map doesn't load tiles after refreshing the page

### ISSUE THREAD

**Issue by d-koppenhagen** [bluehalo/ngx-leaflet#104]
Hi ya'all,

I recently started to use ngx-leaflet in one project. When I use the following code, I have the problem that the map shows only all map tiles when navigating via my app (using the buttons) to the page. As soon as I reload the page using the reload button from the browser (or as I just enter the url directly), the page show just a small tile and the rest of the area where the map should be visible stays in gray color (see attached picture). Also when I use my phone (iPhone) to display the site, I can't see the whole map.

![screen shot 2017-12-04 at 16 50 51](https://user-images.githubusercontent.com/4279702/33572435-383ccbf6-d933-11e7-9d0c-16c2aa4d4b20.png)

I found out that when I resize the browser window manually, the tiles are loaded. So it seem to be a problem with the  calculation probably?

Do you have any Idea how to solve this problem?

File `map.component.html`:
```html
<div leaflet
  [leafletOptions]="leafletOptions"
  [leafletBaseLayers]="baseLayers"
  [leafletLayersControlOptions]="layersControlOptions"
  (leafletMapReady)="onMapReady($event)">
</div>
```

File `map.component.css`:
```css
div.leaflet-container {
  position: absolute !important;
  width: 100%;
  height: calc(100% - 105px);
}
```

File `map.component.ts`:
```ts
import { Component, OnInit } from '@angular/core';
import * as L from 'leaflet';

// Open Street Map Definition
const layOsm: L.TileLayer = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  maxZoom: 19,
  attribution: 'Map-Name',
  detectRetina: true
});

@Component({
  selector: 'gpst-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent implements OnInit {
  // Values to bind to Leaflet Directive
  leafletOptions: L.MapOptions = {
    zoom: 6,
    center: L.latLng(51.163375, 10.447683)
  };
  baseLayers: {[layerName: string]: L.Layer} = {
    'openstreetmap': layOsm
  };
  layersControlOptions: L.ControlOptions = { position: 'bottomright' };

  constructor() { }

  ngOnInit() { }

  onMapReady(map: L.Map) {
    console.log(map);
  }

}
```

**Informaion:**
- Google Chrome Version: 62.0.3202.94
- Angular-CLI Version: 1.5.0
- Angular Version: 5.0.5
- Angular Material Version: 5.0.0-rc.2
- @asymmetrik/ngx-leaflet Version: 2.5.1

Thanks in advance for your help.

**Comment by mcurtis22** [comment]
Hi @d-koppenhagen, do you mind also showing how your selector is used? This issue is not specific to ngx-leaflet. Without looking at more code I can tell you some common pitfalls:

1. Using CSS rules for width and height with percentage (%) values. This normally doesn't cause problems unless the ngx-leaflet directive is on an element that has not had its width/height explicitly set. You could try using viewport-percentage units  (`vh` or `vw`) which can be [read about here](https://developer.mozilla.org/en-US/docs/Web/CSS/length).

2. Using `ngIf` or CSS rule `display: none`. Both of these turn your Angular component into a 0 size element. After an `ngIf` is true or `display:none` is reversed, your problem may be solved by having the leaflet map call `invalidateSize` after one of those events happen.

3. If neither of these suggestions are applicable, try adding a `setTimeout` call that then has the leaflet map call `invalidateSize`.

Hopefully that helps, if not, please feel free to add more detail.

PS: I did not see an attached picture.

**Comment by d-koppenhagen** [comment]
hey @mcurtis22 Thanks for the fast response (sorry I just edited my first comment, now the picture should be there). 
The selector `gpst-map` for my component is not embedded in any othe component directly- the component will be used by the router in the`<router-outlet>`. 
I've already tried to use `invalidateSize` and also the `setTimeout` function but without any success. Probably I used it at a wrong place?

**Comment by d-koppenhagen** [comment]
Okay, after a bit try and error I was able to find out that the following code doesn't solve the issue: 
```ts
 onMapReady(map: L.Map) {
    map.invalidateSize();
 }
```

But changing it to the following will solve the issue (even if the time is set to zero):
```ts
 onMapReady(map: L.Map) {
    setTimeout(() => {
      map.invalidateSize();
    }, 0);
 }
```

Thanks for giving me some hints.

**Comment by mybluedog24** [comment]
Hi, I have the same issue and d-koppenhagen's solution (with or without `setTimeout`) doesn't work (I tried differnt timeout value).

I'm using it in Ionic and here is my code:
**HTML:**
```Javascript
  <ion-row *ngIf="viewMode === 'map'" style="width:100%; height:100vh;">
    <div class="map" style="width:100%; height:100vh;"
     leaflet
    (leafletMapReady)="onMapReady($event)"
     [leafletOptions]="mapOptions">
    </div>
  </ion-row>
```
**ts:**
```Javascript
...
import * as L from 'leaflet';
...
this.mapOptions = {
		layers: [
			L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {}),
		],
		zoom: 8,
		center: L.latLng([43.7974909,-79.4250085])
	};
...
onMapReady(map) {
	setTimeout(() => {map.invalidateSize(true)},1000);
	// map.invalidateSize(true);
```


\
\
\
\
Here's the walkthrough: at the beginning the map will not show up until I change the `wiewMode`:
![fireshot capture 226 - ionproperty - http___localhost_8200_ _tabs-page_search_page-property-search](https://user-images.githubusercontent.com/15975931/41004632-849d5e4e-68e8-11e8-9021-2aa7ebdacfbb.png)
\
\
When I first time click the `Map` button, the map displays correctly.
![fireshot capture 222 - ionproperty - http___localhost_8200_ _tabs-page_search_page-property-search](https://user-images.githubusercontent.com/15975931/41004628-846ce638-68e8-11e8-927d-dff2b06e14f0.png)
\
\
But after I change it to List and change back to Map view, the tile layer can't display.
![fireshot capture 223 - ionproperty - http___localhost_8200_ _tabs-page_search_page-property-search](https://user-images.githubusercontent.com/15975931/41004630-84825e32-68e8-11e8-8794-f675aa691177.png)
\
\
Also I tried use `[hidden]="viewMode !=='map'"` but it shows like this, unless I resize the window:
![fireshot capture 225 - ionproperty - http___localhost_8200_ _tabs-page_search_page-property-search](https://user-images.githubusercontent.com/15975931/41004631-848d04ea-68e8-11e8-83ce-e9616fb37d65.png)
\
\
I'm thinking maybe is because invalidateSize() doesn't work?

Thanks for your help!

**Comment by reblace** [comment]
@mybluedog24 In your original approach (using *ngIf), you're running into the issue where you can't reuse tile layers between instances of a map. You create the tile layers in `mapOptions`, but I bet you aren't recreating them when the map is recreated when *ngIf evaluates to true. This is a slightly frustrating feature of Leaflet. When layers are added to the map, they are changed by the map. If you try to reuse those layers again, they just won't work. One way to fix this is to create a wrapper component for the map that just contains the default map options and maybe input/output bindings for the marker you're putting on the map and whatever interactions you want to allow. Then, you could put the *ngIf on that component. When *ngIf evaluates to true, your map wrapper component is created and the map is created (and so you end up with new instances of the layers). When *ngIf evaluates to false, both the wrapper and the map itself are destroyed, ensuring that the next time it's created, it will be completely recreated with new layers and everything.

If you want to save state between viewModes (e.g., zoom/pan), you'd probably be better off using the `[hide]` approach in your second example. Here, you just need to move your `invalidateSize` call into logic that is triggered by the change in state for `viewMode`. `(leafletMapReady)` is only invoked when the map is created. `[hide]` doesn't create or destroy the map, it just changes the CSS on the map DIV so that it's hidden. But, it's still in the DOM. `(leafletMapReady)` would only get invoked if you removed the map directive from the DOM using *ngIf as in your first example.

Hope this helps.

**Comment by mybluedog24** [comment]
@reblace  Thank you so much! You saved me! Thank you for pointing out that using `[hidden]` for saving state between viewModes. I'm using the `[hidden]` approach. Passing the map variable by `(leafletMapReady)` and called `invalidateSize()` after switch to map view. Here's my code:
**HTML:**
```Javascript
...
  <button ion-button (click)="viewMode='map';invalidateSize();">Map</button>
...
  <ion-row [hidden]="viewMode !== 'map'" style="width:100%; height:100vh;">
    <div class="map" style="width:100%; height:100vh;"
     leaflet
    (leafletMapReady)="onMapReady($event)"
     [leafletOptions]="mapOptions">
    </div>
  </ion-row>
```
**ts:**
```Javascript
...
import * as L from 'leaflet';
...
map: any;
...
this.mapOptions = {
		layers: [
			L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}', {}),
		],
		zoom: 8,
		center: L.latLng([43.7974909,-79.4250085])
	};
...
onMapReady(map) {
	this.map = map;
}
...
invalidateSize() {
	if (this.map) {
		setTimeout(() => {this.map.invalidateSize(true)},100);
	}
}
```

**Comment by vaydich** [comment]
Hi.

I have the same problem. On load, zoom, move or resize - each time some of tile doesn't load correctly.

![cli](https://user-images.githubusercontent.com/12065515/43888004-0e4f47ca-9bc9-11e8-9b6a-5267cdae24a7.png)

**package.json**

```
{
  "name": "noname",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-generic-table/column-settings": "^4.13.0",
    "@angular-generic-table/core": "^4.12.0",
    "@angular/animations": "6.1.0",
    "@angular/cdk": "^6.4.1",
    "@angular/common": "6.1.0",
    "@angular/compiler": "6.1.0",
    "@angular/core": "6.1.0",
    "@angular/forms": "6.1.0",
    "@angular/http": "6.1.0",
    "@angular/platform-browser": "6.1.0",
    "@angular/platform-browser-dynamic": "6.1.0",
    "@angular/router": "6.1.0",
    "@asymmetrik/ngx-leaflet": "^4.0.0",
    "@asymmetrik/ngx-leaflet-draw": "^3.1.0",
    "@asymmetrik/ngx-leaflet-markercluster": "^1.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.2.1",
    "@ngx-gallery/core": "3.0.2",
    "@ngx-gallery/lightbox": "3.0.2",
    "@ngx-progressbar/core": "^5.0.1",
    "@ngx-progressbar/http": "^5.0.1",
    "@types/leaflet": "^1.2.6",
    "@types/leaflet-draw": "^0.4.11",
    "@types/leaflet-rotatedmarker": "^0.2.1",
    "@types/leaflet.markercluster": "^1.0.3",
    "bootstrap": "^4.0.0",
    "clappr": "^0.2.95",
    "core-js": "^2.4.1",
    "jquery": "^3.3.1",
    "leaflet": "^1.3.1",
    "leaflet-draw": "^1.0.2",
    "leaflet-rotatedmarker": "^0.2.0",
    "leaflet.markercluster": "^1.3.0",
    "ng2-dragula": "^2.0.2",
    "ngx-device-detector": "^1.3.0",
    "primeicons": "^1.0.0-beta.9",
    "primeng": "^6.0.0",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "tether": "^1.4.4",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular/cli": "^6.1.0-rc.3",
    "@angular/compiler-cli": "6.1.0",
    "@angular/language-service": "6.1.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~10.5.4",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^1.2.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "^2.7.2"
  }
}

```

**gis-desktop.component.html**

```
<div id="MapContainer"
    leaflet
    [leafletOptions]="options"
    (leafletMapReady)="onMapReady($event)"
    (leafletMarkerClusterReady)="onMarkerClusterReady($event)">
</div>
```

**gis-desktop.component.ts**

```
import { Component, ElementRef, HostBinding, ViewChild } from '@angular/core';
import { GlobalEventsManagerService } from '../../../_shared/service/global-events-manager.service';
import { CoreConfig } from '../../../core/core.config';
import { SharedUtils } from '../../../_shared/utils/utils';
import { UserDataService } from '../../../_shared/service/user/user-data.service';
import { electricTrains } from '../../../_shared/interface/transport';

// Leaflet import
import * as L from 'leaflet';
import 'leaflet.markercluster';
import 'leaflet-rotatedmarker';

@Component({
  selector: 'app-gis',
  templateUrl: './gis-desktop.component.html',
  styleUrls: ['./gis-desktop.component.css']
})

export class GisDesktopComponent {

  @HostBinding('class') classes = 'flex-column-body';

  MAP: any;

  // Layers
  LAYER_OSM = {
    id: 'openstreetmap',
    name: 'Open Street Map',
    enabled: true,
    layer: L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      attribution: 'Open Street Map'
    })
  };

  // Initialise base layers
  baseLayers = {
    'Open Street Map': this.LAYER_OSM.layer
  };

  // Initialise cluster group-list
  camerasClusterGroup = L.markerClusterGroup({});

  // Initialise the FeatureGroup to store editable layers
  editableLayers: any = new L.FeatureGroup();

  // Initialise leaflet options
  options = {
    zoom: 11,
    center: L.latLng([56.283883704796445, 44.036083924804586]),
    layers: [this.LAYER_OSM.layer]
  };

  // Initialise leaflet draw options
  drawOptions = {
    position: 'topright',
    draw: {
      polygon: {
        allowIntersection: false, // Restricts shapes to simple polygons
        drawError: {
          color: '#e1e100', // Color the shape will turn when intersects
          message: '<strong>Вы не можете так рисовать<strong>' // Message that will show when intersect
        },
        shapeOptions: {
          color: '#97009c'
        }
      },
      polyline: false,
      circle: false,
      circlemarker: false,
      rectangle: false,
      marker: false
    },
    edit: {
      featureGroup: this.editableLayers, // REQUIRED!!
      remove: true
    }
  };

  // Booleans
  layerControl: any = false;
  bIsDestroy = false;

  constructor(private _coreConfig: CoreConfig,
              private _globalEventsManagerService: GlobalEventsManagerService,
              private _elementRef: ElementRef,
              private _userDataService: UserDataService) {}

  ngOnInit() {}

  onMapReady(map: L.Map) {
    this.MAP = map;
    this.layerControl = L.control.layers(this.baseLayers, {}, { position: 'bottomright' }).addTo(this.MAP);
    this.MAP.zoomControl.setPosition('topright');
    this.renderMovableObjects(electricTrains);
  }

  ngOnDestroy() {
    console.warn('DESTROY_MAP_COMPONENT');
    this.bIsDestroy = true;
  }

}

```

**gis-desktop.component.css**

```
#MapContainer {
  width: 100%;
  height: 100%;
}

.flex-column-body { // it's parent of #MapContainer
    position: relative;
    flex: 1 1 auto;
    order: 1;
    overflow-y: auto;
}
```

![map1](https://user-images.githubusercontent.com/12065515/43888578-b2ef907c-9bca-11e8-828e-7a1a37e65850.png)

And some of tile requests getting more time then should i think...

![waterfall](https://user-images.githubusercontent.com/12065515/43889123-032772ac-9bcc-11e8-8f6e-4d96217a10b6.png)


Can you explain me what's the problem?

up

in some browser it solve when resize

**Comment by mybluedog24** [comment]
@vaydich Did you try d-koppenhagen's solution? If resize solved the problem try call the `invalidateSize()`.

d-koppenhagen's solution:
```Javascript
 onMapReady(map: L.Map) {
    setTimeout(() => {
      map.invalidateSize();
    }, 0);
 }
```

**Comment by vaydich** [comment]
@mybluedog24, yes i've already tried and it solved. Thanx

**Comment by d-koppenhagen** [comment]
@mybluedog24 well it's more a workaround, not really a "good" solution I think.

**Comment by vaydich** [comment]
@d-koppenhagen yes but there is no better solution as i understand

**Comment by PeterKutschera** [comment]
Another possible reason for this problem, so check this.

I had the same problem and none of the ideas above did help.

Then I found out that I missed to add all the
 node_modules/leaflet*/.../*.css
in angular.json (the new name for .angular-cli.json) in the "styles" section.

**Comment by leogilardi6** [comment]
Another thing you can do is to use an `*ngIf="show" `directive and after the view init, set it on true. That worked for me. I guess the problem  is when the map is loaded, so if you wait until the component is fully loaded, it'll work properly.

**Comment by RaederDev** [comment]
I just ran into the same issue. The problem with the timeout solutions posted above is that they will not work on very slow devices because you might run into a race condition.

The problem occurs for me when I put the leaflet directive into a custom element of my own. The issue seems to be that the parent container has a size of 0 for a few milliseconds when the map get's initialized. You can see this here (0ms and 500ms):
https://i.imgur.com/9DMijJH.png

The solution I came up with seems to work 100% of the time and on all devices no matter how slow:

- Install angular-resize-event
- Add resize event listener to map container
- Add onMapReady event to map container
 - invalidateSize() every time you get a resize event

```
<div class="map-container"
     leaflet
     [leafletOptions]="options"
     (leafletMapReady)="onMapReady($event)"
     (resized)="onResized()"
></div>
```

```
import {Component} from '@angular/core';
import {latLng, Map, MapOptions, tileLayer} from "leaflet";

@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.scss'],
})
export class MapComponent {

  public options: MapOptions = {
    zoom: 12,
    center: latLng(48.206993, 16.363670),
    zoomControl: false,
    layers: [
      tileLayer('https://{s}.wien.gv.at/basemap/bmapgrau/normal/google3857/{z}/{y}/{x}.png', {
        maxZoom: 18,
        minZoom: 1,
        subdomains: [
          'maps', 'maps1', 'maps2', 'maps3', 'maps4'
        ],
        attribution: ''
      })
    ]
  };

  public map: Map = null;

  onMapReady(map: Map) {
    this.map = map;
  }

  onResized() {
    if (this.map) {
      this.map.invalidateSize();
    }
  }

}

```

**Comment by MikeDabrowski** [comment]
In my case, the problem is that invalidateSize does not work even if fired from console or on keypress. So far the only thing that works for me is to manually change current layer in layersControl. I also tried to subscribe to router.events and change map options and layersControl but this didn't help. 

Edit: 
I was able to get the map refresh when i moved layers property from [leafletOptions] to [leafletLayers]. This way I don't need invalidateSize() and any changedetection trigger. However, if I first change layer to other map (let's say OSM), then navigate somewhere and come back, the map will revert to default one (which will be refreshed), but when I manually change it to OSM again, it will give gray fields. 🤷‍♂

**Comment by WayneRiesterer** [comment]
I was facing a situation where the tiles wouldn't re-render after routing away from the map host component and back again. The markers were visible, but no base layer.

My base layer (ESRI Satellite) would return if I refreshed the page or toggled an Open Street Map overlay on and then off again.

I fixed this using the following:
- set map parameters in ngOnInit within the map host component
- use (leafletMapReady)="onMapReady($event)" to set a reference to the map in the map component
- use ngOnDestroy to remove the map using this.map.remove()

I could use a mapReady flag in combination with *ngIf, but it's working fine without it.

I hope this helps someone else as it has taken me a few hours to work this one out. I tried invalidateSize and this didn't work; with or without a setTimeout. Without looking into it too much, I thought this might get the map to redraw and bring the tiles back, but it didn't work.

Here's some code snippets which should be easy enough to follow:

**template**
```
<div id="map" leaflet
     [leafletOptions]="mapOptions"
     [leafletLayersControl]="layersControl"
     (leafletMapReady)="onMapReady($event)">
  <div *ngFor="let marker of markers" [leafletLayer]="marker"></div>
</div>
```

**component**
```
mapOptions: MapOptions
layersControl: LeafletControlLayersConfig
markers: Array<Layer>

map: Map

constructor(private mapService: MapService) {}

ngOnInit(): void {
  this.mapOptions = this.mapService.getMapOptions()
  this.layersControl = this.mapService.getLayersControl()
  this.markers = this.mapService.getMarkers()
}

onMapReady(map: Map): void {
  this.map = map
}

ngOnDestroy(): void {
  this.map.remove()
}
```

**Comment by evindunn** [comment]
I had the same problem with sass when calling:
```scss
@import "~leaflet/dist/leaflet.css";
@import "~leaflet-draw/dist/leaflet.draw.css";
```
In my .component.scss rather than in global styles.scss. Works perfectly fine after switching.

**Comment by FlowCAD** [comment]
The best answer I have seen about this point is here :
https://stackoverflow.com/a/53240986/5138332
Really easy to implement !

**Comment by dineshkumar02** [comment]
In my case, I need to change the tileLayer option url from http to https.

```
"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" -> This one working

"http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" -> This one worked and started giving me 403 forbidden
```

**Comment by michalsisak** [comment]
None of the solutions above worked for me. What did was waiting to show the up after the page was ready with `ngAfterViewInit` life cycle.


```typescript
showMap = false;

ngAfterViewInit(): void {
  // Wait to show the map until the site is ready
  this.showMap = true;
}
```

```html
// Angular control flow syntax but regular *ngIf should work as well
@if (showMap) {
  <div
    leaflet
    [leafletOptions]="options"
    [leafletLayers]="layers"
    (leafletMapReady)="onMapReady($event)"
    id="map"
  ></div>
}

```
