### ISSUE TITLE
Refresh of Angular app on every mouse move (the pointermove event)

### ISSUE THREAD

**Issue by sashuk** [bluehalo/ngx-leaflet#110]
Hello! Seems like adding a **ngx-leaflet** to the application makes the application to update every mousemove.

Way to recreate:

1. Deploy any boilerplate, for example, the https://github.com/haoliangyu/ngx-leaflet-starter

2. Create and register the following component

```typescript
import {Component} from "@angular/core";

@Component({
    selector: "test",
    template: `<h1>{{componentValue}}</h1>`
})
export class TestComponent {
    _componentValue: String = 'lalala';
    constructor() { }
    set componentValue(value) {}
    get componentValue() {
        console.log('Somebody is getting the value');
        return this._componentValue;
    }
}
```

3. Add it somewhere in the application layout near the actual map component

4. Load the app and see that on every mouse move the TestComponent is redrawn (the `get componentValue()` of `TestComponent` is called)

5. If the map is removed, then such behavior can not be observed

So, it seems like Leaflet makes the entire Angular app to update in reply to **pointermove** (**mousemove**) event.

**Comment by reblace** [comment]
I'm looking at this now. I'm not sure what's causing it but I did reproduce it. At first I was expecting this because the layers binding is using DoCheck and IterableDiffers for change detection, but that shouldn't cause everything to do a dirty check on mouse move. Thanks for bringing this up!

**Comment by reblace** [comment]
The root cause of the issue is that Zone.js monkey patches a lot of stuff (including mouse events) so that Angular can trigger change detection based on them. Leaflet registers a bunch of those events (apparently including mousemove), so Angular is doing change detection pretty much constantly in response to mouse movement. That's why the gets are being called, so angular can do its dirty checks.

Zone.js provides a way to get around this by running code outside of angular (https://blog.thoughtram.io/angular/2017/02/21/using-zones-in-angular-for-better-performance.html) which does seem to be the right solution for this situation. I'll implement it and make sure it doesn't cause any other issues and if all goes well I'll roll it into the plugin as a minor release.

**Comment by sashuk** [comment]
@reblace Thank you very much, looking forward to it!

**Comment by reblace** [comment]
I released a new minor version that should address it. v2.6.0. Please check it out and let me know if you have any issues with it. I did a fair bit of testing to make sure there weren't unintended side effects, but it's hard to cover all potential use cases.

**Comment by alexgoldstone** [comment]
My project is young and therefore my usage of ngx-leaflet is reasonably trivial so far but I just wanted to confirm that at least for me (using Angular 5) the upgrade was seamless and everything has continued to work. Thank you for the time you have put into this project.

**Comment by sashuk** [comment]
@reblace Thank you very much for the fix! The **pointermove** event is not fired now indeed, but I've noticed that the **pointerdown** still fires the Angular update (I guess as well as **pointerup** and **pointercancel**). As I see this situation - if the Leaflet in intergrated into the Angular application without `ngx-leaflet`, then it becomes a hell to work with. However, using the `ngx-leaflet` can provide pain-free work with Lealfet in Angular, as it **constraints** all the raw-Leafet side-effects.

**Comment by reblace** [comment]
I don't see any of the events triggering dirty checks. Is your example still exactly the same as the first one you shared?

Also, I rolled an ng5 update into this 2.6 release, which I just realized isn't actually backward compatible. So, I'm going to re-release 2.6 as 3.0 and then release a 2.6.1 that downgrades back to ng4.

**Comment by reblace** [comment]
Just for some context about my decisions - there is a bit of a balancing act here. If I push too much stuff out of the angular zone, it puts more of a burden on developers to trigger change detection when they are using any of the events in Leaflet. With the more advanced topics like zones, change detection, and differs, I try to avoid forcing them on the casual user cause it leads to a lot of issues being submitted and questions on stack overflow.

My priority with your specific issue was to eliminate the change detection triggering on mousemove since that's way too excessive and crushes performance even when users aren't interacting with anything. I'm willing to accept change detection on click/mouseup/mousedown/window resize since those interactions trigger change detection normally in Angular components.

My long-term plan to help mitigate some of these issues is to expose a lot of the events using EventEmitters and @Output, that way I can internally trigger change detection on those events specifically. But in the interim, I'll probably leave it like it is now (and I'm gonna close this issue).

Thank you for pointing out this issue though, as I didn't even realize how zones worked until I dug into this issue. If you have any other issues, feel free to open new issues or add a comment to this one.

**Comment by sashuk** [comment]
@reblace Thank you very much for the explanation! Got it, so, for now we stick with the change detection on **mouseclick**, which happens much less often than the **mousemove** events anyway :)
