### ISSUE TITLE
fitBounds  do not works on a circle

### ISSUE THREAD

**Issue by sgrillon14** [bluehalo/ngx-leaflet#115]
```
c: Circle;

this.c = circle([ data.lat, data.lon ], { radius: data.radius , color: data.color });

const circleStart = {
  id: data.id,
  name: data.name,
  enabled: true,
  layer: this.c
};

this.fitBounds = this.c.getBounds();   <<<<  KO
```

**Comment by reblace** [comment]
The specific issue you're running into here is that ```this.c.getBounds()``` doesn't work until after the circle is added to the map. You'd have to register a listener on the layer add event and then call fitBounds in there. Something like this:

```
this.c.on('add', () => { this.fitBounds = this.c.getBounds(); });
```

You may run into a warning about changes after change detection because the callback gets invoked during the change detection that added the layer... so, a quick solution for that is to inject the ChangeDetectorRef and manually trigger change detection:

```
this.c.on('add', () => { this.fitBounds = this.c.getBounds(); });
this.changeDetector.detectChanges();
```

**Comment by sgrillon14** [comment]
thanks @reblace your solution works!! You can close this issue.
