### ISSUE TITLE
Angular UI not updating after 2.6.0

### ISSUE THREAD

**Issue by jessenic** [bluehalo/ngx-leaflet#118]
The UI on the same page as the map stopped updating after upgrading past 2.5.0. I need to update variables that affect the UI outside leaflet on click events from buttons inside marker popups. I have a button in popups, that opens a dialog in the Angular HTML component.

I tried to go around this issue by adding manual calls to ChangeDetectorRef.detectChanges(), and while that worked for the popups, regular Angular UI stopped partly updating.

When the user clicks a button inside the marker popup, a dialog is opened by setting this.dialogOpen = true.
Angular template: `<div *ngIf="dialogOpen"><button (click)="dialogOpen = false">Close</button></div>`
Clicking the close button does not close the dialog after 2.6.0, unless the user interacts with other page elements that cause a change detection.

**Comment by shlomir** [comment]
The same here.
Markup (binding)  is not being update after JS changes.

**Comment by reblace** [comment]
If you're encountering this issue, fall back to 2.5.x for now.

Can you provide some code samples of your specific use cases/issues?

This is a zone issue. I wanted to move towards having the Leaflet stuff run outside of angular's zone to avoid the overhead of mouse move events causing constant dirty checking. But, obviously it makes things more complicated when it comes time to add interactions like this.

**Comment by chriszrc** [comment]
Have you followed the development of the rxjs patch for zone.js? 

https://github.com/angular/angular/issues/16092#issuecomment-356725783

more here too (https://github.com/angular/zone.js/issues/830)

Without that patch, things like making a router.navigate call from inside of leaflet/ngx-leaflet (3.0.1) (like updating a route when clicking on a marker) failed in very odd ways. With the patch, everything seems to be working again, except layer removal in ngx-leaflet.

Removing layers or even rebuilding the layer array appears to be having no effect on removing the layers on the map. Adding is working. I'm assuming this is a zone related issue, although looking at the ngx-leafet source, I can't see what the problem would be. Have you or anyone else experienced this issue?

**Comment by reblace** [comment]
I wasn't aware of the patch. I'll take a look, thanks for the pointer.

I'm working on a fix, but I've been debating rolling back to the old behavior that making the out-of-angular zone change something you have to opt into. The issue is most people don't expect to have to do anything extra to make change detection work when they are doing something inside of a leaflet callback (even if we fix the issues with zone management).

**Comment by chriszrc** [comment]
Yeah, check out the patch, because with that, at least it looks like angular code running from within leaflet code is prompting the right ui updates. And it's as easy as adding that one line to the angular polyfills. 

Any ideas though about the layer removal? Because that's just all leaflet code, so shouldn't be affected by all this right?

**Comment by reblace** [comment]
Do you have a simple example in GitHub I can check out? Can you make a standalone ngCLI project to reproduce the problem?

It would be odd for the layer change detection to be affected since that's all setup and managed in Angular's zone to begin with and shouldn't be affected by this.

**Comment by mattdsteele** [comment]
I'm seeing the same issue. Here's a demo based off the Angular CLI: https://github.com/mattdsteele/ng-leaflet-zones

In particular, [updating a binding inside a marker's click handler](https://github.com/mattdsteele/ng-leaflet-zones/blob/master/src/app/app.component.ts#L35) does not get applied.

Reverting to 2.5.x works.

**Comment by chriszrc** [comment]
@mattdsteele try just adding the following to the src/polyfills.ts file, this fixed that issue for me:

```
/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.
// solves many issues with zone and rxjs, which is used by router :( https://github.com/angular/angular/issues/16092 , https://github.com/angular/zone.js/issues/830
import 'zone.js/dist/zone-patch-rxjs';
```

**Comment by chriszrc** [comment]
@reblace I will try to reproduce the layer change detection separately -

**Comment by mattdsteele** [comment]
@chriszrc Adding the `zone-patch-rxjs` did not resolve this, unfortunately. I get the same behavior.

```
> npm ls zone.js
+-- @angular/cli@1.6.1
| `-- zone.js@0.8.20  deduped
`-- zone.js@0.8.20
```

**Comment by chriszrc** [comment]
@mattdsteele yeah, you're right, in my case, i was dealing with rxjs issues specifically, guess that fix is more specific that I thought. In your case, you can make the example work by running change detection yourself, although of course this is less than ideal:

```
constructor(
    private cd:ChangeDetectorRef
  ){}

...

mark.addEventListener('click', evt => {
      console.log('clicked tooltip');
      this.tooltipClickedTimes++;
      this.cd.detectChanges();
    });
```

and then it does all work-

**Comment by reblace** [comment]
(Updated)

Having to trigger change detection is by design (at least by design due to a change made in 2.6.x). Admittedly, this change was not backwards compatible, but I didn't realize it would be this much of an issue.

There's a description of the reasoning in the README. It's due to a performance issue that you may or may not be aware of (you can also see https://github.com/Asymmetrik/ngx-leaflet/issues/110 for context). Basically, Angular monkey patches code into all interaction event callbacks so that it knows when it might need to run change detection.

Leaflet specifically registers a callback on mousemove, which means that change detection is triggered on all mouse move events. You can see that issue above to see some example code that describes the issue. I've never really noticed the actual performance impact, but it all depends on what you're doing.

The "fix" is to run Leaflet outside of Angular's zone. This prevents Angular from monkey patching registered event callbacks. But, it also has the side effect that those registered callbacks will no longer trigger change detection when you modify things.

There are two solutions (theoretically):

1. The first is to manually call ```detectChanges``` on a reference to ```ChangeDetectorRef```. @chriszrc shows how you'd do that and I think it's in hte README now.

2. The second is inject ```NgZone``` and then wrap your changes in a call to ```NgZone.run()```. I think this will have the same end result as the above.

I can/will provide a tutorial with more details and add more explanation to the README to make sure this is clear. I also plan to fix this (or at least deal more fully with it) soon. 

I was torn about making this change, or making it something that you have to opt into, so that it isn't confusing to people who don't care about the performance impact. That decision is TBD, but I hope to do it soon (next couple weeks). For now, you can use 2.5.x. If you need an ng5 build, I can prioritize backing the change out of 3.x so an ng5 build is available. But, I believe that 2.x is compatible with ng5 already, so that shouldn't be necessary.

Thanks for your patience and understanding.

**Comment by chriszrc** [comment]
Ok, here's where it gets interesting. If I include the "zone-patch-rxjs", I can get the tooltip clicked to update without doing anything special, as long as I change the "tooltipClickedTimes" to an observable and use "async" in the template. 

```
tooltipClickedTimes = new BehaviorSubject<number>(0);

let count = 0;
mark.addEventListener('click', evt => {
      console.log('clicked tooltip');
      this.tooltipClickedTimes.next(count++)
  });

//and in the template
{{tooltipClickedTimes | async }}
```

I realize many angular users aren't adopting a strict OnPush change detection strategy that requires all monitored values to be observables, but this does solve the problem, without introducing anything unexpected-

**Comment by bisonfoutu** [comment]
@reblace Hey, thanks for your contribution towards this issue !
I believe the 2nd solution you mentioned (the one with `NgZone.run()`) should also be mentioned in the README.
At first I opted for the `detectChanges` way, but as the component containing Leaflet also had other child components, they were considerably slowed down. 
I was able to solve this by using `NgZone.run()`, which in my opinion is also way more precise.

**Comment by reblace** [comment]
@mattdsteele sorry it took so long to look at this.

Your issue is that the Leaflet callbacks are running outside of the Angular zone. There's some details in the README, but basically, Angular uses zones to determine what events to monkey patch in order to automatically perform change detection. When I went to v3 of the ngx-leaflet plugin, I made a change (for the sake of performance) that runs all of the Leaflet code outside of the Angular zone. Without the change, every Leaflet event (including mouse move) triggers change detection, which can get expensive for larger or more complex apps.

The solution is that when you are making an Angular-relevant change inside of a Leaflet event handler, you need to trigger change detection. There's a couple ways to make this happen. You can either run the change inside Angular's zone using:

```
import { Component, NgZone } from '@angular/core';
import { tileLayer, latLng, Layer, marker, icon, MarkerOptions } from 'leaflet';
import { OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';
  options = {
    layers: [
      tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: '...'
      })
    ],
    zoom: 5,
    center: latLng(46.879966, -121.726909)
  };
  tooltipClickedTimes = 0;
  layers: Layer[] = [];
  constructor(private zone: NgZone) {} // Inject the Angular zone reference
  ngOnInit() {
    console.log('initting');
    const markerOptions: MarkerOptions = {
      icon: icon({
        iconSize: [25, 41],
        iconAnchor: [13, 41],
        iconUrl: 'assets/marker-icon.png',
        shadowUrl: 'assets/marker-shadow.png'
      })
    };
    const mark = marker(latLng(46.879966, -121.726909), markerOptions);
    mark.addEventListener('click', evt => {
      console.log('clicked tooltip');

      // Make changes inside Angular's zone using the run() function
      this.zone.run(() => {
        this.tooltipClickedTimes++;
      });

    });
    this.layers.push(mark);
  }
  forceUpdate() {
    this.tooltipClickedTimes++;
  }
}
```

You can also inject a reference to the ChangeDetector and manually trigger change detection as described in the 3.x README: https://github.com/Asymmetrik/ngx-leaflet#a-note-about-change-detection

Over time, I'll add support for event emitters for the various map events, and as part of that I'll be able to ensure that the callbacks are happening inside Angular's zone. But, for now, either of these options is the correct way to handle this.

@chriszrc - does this also address the issue you were encountering?

**Comment by reblace** [comment]
@bushybuffalo I will add the NgZone.run() method as the preferred method to the README. Thanks!

**Comment by reblace** [comment]
I've updated the README to include the suggestion to use NgZone.run and with a couple extra pointers to the issue.

**Comment by reblace** [comment]
I'm planning to resolve this issue.

I believe that the strategies outlined in the README are adequate to address any issues people encounter when working with Leaflet events that are happening outside of the Angular zone.

Just to recap, you either want to wrap your code that is changing the component state in a call to NgZone.run() or you can inject a reference to ChangeDetector and call to detectChanges manually.

If anyone has any issues that are not resolved in moving to the latest 2.x and 3.x versions, please let me know. Thanks!
