### ISSUE TITLE
Google API Key ?

### ISSUE THREAD

**Issue by codemonkeyneo** [bluehalo/ngx-leaflet#170]
Hi ,

I use your component and its awesome but wondering where do you provide the API Key for google maps. Im just worried that when I release the application it will be blocked if there are too many requests.

Pretty much I implemented it following the sample you give

https://asymmetrik.com/ngx-leaflet-tutorial-angular-cli/

```
layers: [
      tileLayer('http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}', {
        maxZoom: 20,
        subdomains: ['mt0', 'mt1', 'mt2', 'mt3'],
        detectRetina: true
      })
    ],
```

But there is no API Key which I belive is required to legally use google tiles ?

Thanks for any help.

**Comment by reblace** [comment]
If you want to use google maps, you’ll want to get your own API key.

**Comment by codemonkeyneo** [comment]
Thank you for the reply , I understand about API Key , question is more how it fits in with the example provided. I could easily add additional querystring of key= to the end of the tileLayer request but wasnt sure this is correct or how it should work. Previous version of work with google maps I use the script tag with googleapis and provide the key.

**Comment by reblace** [comment]
Oh yeah, I see what you're asking. We don't use Google Maps in production. We use our own map server, MapBox, OpenStreetMap, etc. Even Leaflet advises against trying to use the Google Maps API with Leaflet because according to their ToS, you are required to use their SDK (https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#i-want-to-use-google-maps-api-tiles-with-leaflet-can-i-do-that).

Map Box is pretty sweet. They provide you the ability to customize maps and pay for commercial use. I didn't realize Google Maps required use of the SDK. I'll be updating the tutorial soon anyways, so I'll probably switch it to use OSM just to avoid confusing people about Google's ToS.

**Comment by lfreneda** [comment]
@codemonkeyneo did you figure out?

**Comment by codemonkeyneo** [comment]
@lfreneda I just left the current implementation and thought well if Google are allowing the tile layers to be served in this way I will continue as is. The application I have written also uses MapBox and that's the primary tiles layer now and uses an API key.
