### ISSUE TITLE
layersControl - layer cannot be turned on/off if new layer added into overlays

### ISSUE THREAD

**Issue by jamestlc** [bluehalo/ngx-leaflet#182]
Version: 4.0.0

My layersControl setup:
```
layersControl = {
        overlays: {
           'Main Layer': L.tileLayer.wms(...),
           'Second Layer': L.tileLayer.wms(...)
       }
}
```

If I add a new layer by using:

```
const newLayer = L.tileLayer.wms(....);
this.layerControls.overlays['New Layer'] = newLayer;
```

I can see the new layer on the map and the "New Layer" is seen in the layers control.
However, when I try to click the layers control, none of the layer can be turned on/off.

I didn't make use of the layerControlOptions, should I set something for that?
Thank you.

**Comment by reblace** [comment]
Can you provide your complete component code and template? Are you also using [leafletLayers] or providing [leafletOptions]?

**Comment by reblace** [comment]
I tried to reproduce this issue. I modified the "layers-demo" in the ngx-leaflet demo so that the GeoJson overlay is only added to the layers control after the user clicks a button.

The GeoJson layer was added to the control and the control worked as expected. I'm closing this unless you can provide more detail about the specific issue with some code or something that reproduces it.
