### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when "Dynamically changing zoom level, center, fitBounds, etc."

### ISSUE THREAD

**Issue by smoebody** [bluehalo/ngx-leaflet#203]
Hi. First of all, thanks for this awesome module.

Unfortunately i have a problem with the the behaviour described in the API-section under [Dynamically changing zoom level, center, fitBounds, etc.](https://github.com/Asymmetrik/ngx-leaflet#dynamically-changing-zoom-level-center-fitbounds-etc).

Appearently the bi-directional binding is not updated. You can see my example below. Am I doing it wrong or is this a bug?

### Versions:
* Leaflet: 1.4.0
* ngx-leaflet: 5.0.1
* angular*: 7.2.*

### Example on stackblitz
https://stackblitz.com/edit/angular-fjaj5m

cheers

**Comment by smoebody** [comment]
To clarify a bit more: When you drag the map or zoom in or out, the following error appears in the console:
```
ERROR
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'center: undefined'. Current value: 'center: LatLng(0, 0.175781)'.
``` 

Also the console should print the `SimpleChanges` object in the `onChanges()`-method, which is not happening (appearently because of the error)

**Comment by reblace** [comment]
This is actually a result of the fact that you're doing both an input and output binding on these values.

They initialize as undefined. When you pan/zoom/etc, the ngx-leaflet component fires the change out to your map component, which binds the new value directly to your member variable. That change then triggers the input binding to send the change back into the map. That causes the expression already changed error, which is a thing Angular does to try to detect/complain about potentially infinite update loops.

There's usually ways to work around this by binding the input/output separately and adding a setTimeout or something since you know this isn't an infinite loop issue. That will avoid the error but behave the way you want.

I can look into this use case as I might be able to fix it by updating the internal variable before firing the output event emitter. But, I wanted to give you some quick context cause I might not have time to dig into the root of the issue until later.

**Comment by smoebody** [comment]
Thanks for the quick reply.

> This is actually a result of the fact that you're doing both an input and output binding on these values.

But isn't this the suggested way as described in the [documentation](https://github.com/Asymmetrik/ngx-leaflet#dynamically-changing-zoom-level-center-fitbounds-etc) or did i get it wrong?

I also tried to only bind one-way, i.e. with `(leafletZoom)` instead of `[(leafletZoom)]`. This prevents the error, but `ngOnChanges()` is not triggered either. ([code](https://stackblitz.com/edit/angular-tfdcje))

Right now i do not see a way to react on a user zooming in and panning the map. How can i get the bounds and the zoom-level after a user interacted with the map?

**Comment by reblace** [comment]
In this case, I think the error is due to the fact that you initialize the zoom and center values to null.

I will sometimes break apart the input and output bindings as well so that I can avoid cyclical updates. Here's a modded example I made that shows what I mean: https://stackblitz.com/edit/angular-fpwqip

**Comment by reblace** [comment]
Gonna close this since it's been a quiet thread for a few months.
