### ISSUE TITLE
If ngx-leaflet is still needed?

### ISSUE THREAD

**Issue by Swanesse** [bluehalo/ngx-leaflet#208]
Recently, I found a blog entry where it is shown how to use a leaflet with Angular without using ngx-leaflet: https://codehandbook.org/use-leaflet-in-angular/
It is written that you just need to download Leaflet from the official home page and copy the folder to the src/assets.
I wonder if this solution is correct or will not generate problems at a later stage.
Is this solution possible only from the 6th version of Angular?
I know that my question may be offensive to creators, because I challenge the purposefulness of the ngx-leaflet library, but I am asking for your understanding. I want to understand the legitimacy of using the library well, if there is a chance that I will be able to simplify my project as much as possible.

**Comment by Reda1000** [comment]
Hi @Swanesse just evaluating the need of ngx-leaflet as a leaflet wrapper for my company.

The link you provided uses leaflet in a more basic / original way - you might end up rewiring leaflet to your components etc. regarding ChangeDetection, Selectors etc. This could in the end lead to your very own ngx-leaflet-like wrapper.

This can be done with (almost) any JS-Library even before 6th version of Angular.

I would suggest sticking to an angular wrapper library especially if this is a commercial project and you are highly under stress implementing main business logic - if you do it for improving your own skills you can still try but be careful not to [reinventing the square wheel](https://en.wikipedia.org/wiki/Reinventing_the_wheel#Related_phrases).

**Comment by reblace** [comment]
@Reda1000 covers it. This library provides two-way data binding and event output bindings. It also manages the interaction between Leaflet and the Angular zone to keep change detection efficient.  This is nice because it keeps your Angular/Leaflet integration more concise and simpler. There's nothing stopping you from doing this yourself. But, if you wanted your Leaflet integration to be reusable, you'd likely end up writing similar directives. The benefit of using this one is that it's Open Source and maintained. Thanks for the question!
