### ISSUE TITLE
geoJSON function deosn't work with data fetched from a REST API

### ISSUE THREAD

**Issue by kammounmustapha** [bluehalo/ngx-leaflet#219]
I have got a problem with geoJSON function which shows the features from a variable and doesn't show the data fetched from an REST API. 
![image](https://user-images.githubusercontent.com/37082830/56512665-f892a200-6527-11e9-9e16-ed2d6f2930d9.png)
![image](https://user-images.githubusercontent.com/37082830/56512684-034d3700-6528-11e9-84ee-056ca0d67694.png)

![image](https://user-images.githubusercontent.com/37082830/56512438-4064f980-6527-11e9-8211-266804022be9.png)
as you can see the schema of the geojson arrays is quite the same, but it works only when I put it in a variable.

**Comment by reblace** [comment]
Edit: completely changed the answer :)

I think the issue here is you initialize the overlay to a geoJSON object that happened to be created when the `this.feature$` object was uninitialized. That object isn't going to be recreated when you reassign the `this.feature$` variable.

In order to trigger change detection and get this to work, you want to replace the value to which the `this.layersControl.overlays.b` key points to. In other words:

```
.subscribe(res => {
  this.feature$ = res;

  // Ensure that this.layersControl.overlays does not contain a 'b' key until you add it here
  this.layersControl.overlays.b = geoJSON(this.feature$ as any);
});
```

If you have more questions specifically about getting this to work, can you move this question to Stack Overflow? Thanks!

**Comment by kammounmustapha** [comment]
Thank you very much! 
it worked!
