### ISSUE TITLE
How to detect map unload

### ISSUE THREAD

**Issue by patolax** [bluehalo/ngx-leaflet#220]
I want to save selected overlay layers on layers control to local storage so that I can preselect them when the user reloads the map next time.

I tried using leafletMap.on('overlayremove') and overlayadd methods to cache the selected layers, however, the same methods are been called when the map unloads so I end up with an empty list at the end.

Is there a way to detect leaflet map is about to be unloaded, so that I can grab selected layers before they are been removed. (ngOnDestroy is called after all layers have been removed)

**Comment by reblace** [comment]
Stack Overflow is probably a better place to ask this question. Tagged with leaflet and ngx-leaflet. This is more specifically a Leaflet question.

Since I don't have a ton of bandwidth to provide general support, I try to keep issues reported here limited to bugs, defects, and enhancement requests.

I'm not sure what other events you might be able to use for this. Maybe a combination of Angular component lifecycle handlers and leaflet map events to differentiate between when the map is being unloaded and when it's legitimately a user selecting/unselecting the overlays. I'll be curious to hear about the solution you find, though.

**Comment by reblace** [comment]
Closing as per the last comment.
