### ISSUE TITLE
Usage of Leaflet v0.7 vs 1.0 not in documentation

### ISSUE THREAD

**Issue by BBaysinger** [bluehalo/ngx-leaflet#23]
Usage of Leaflet v0.7.x vs v1.0.x is not in documentation as far as I can see. Should this be obvious? BTW, thanks for doing this. I'm excited to get into it.

**Comment by reblace** [comment]
The Leaflet API was relatively stable between 0.7 and 1.0. You shouldn't have to do anything special to use 0.7 other than import  it instead of importing 1.0.

I haven't honestly tested it with 0.7 in a while, so it's possible I've added something that broke compatibility. If you find any issues with 0.7, please report them!

**Comment by reblace** [comment]
Closing this for now. If specific issues with Leaflet 0.7 compatibility arise, please open a new ticket with the specific issue.
