### ISSUE TITLE
Tiles not displaying properly with Angular 8

### ISSUE THREAD

**Issue by Jeremy38100** [bluehalo/ngx-leaflet#234]
Tiles are not displaying properly with Angular 8. I followed README instruction and the css seems to be imported :

![screenshot](https://i.ibb.co/f4GZ9sc/Screenshot-2019-08-28-at-09-22-32.png)

Here the `angular.json`file
```
...
"styles": [
  {
    "input": "src/theme/variables.scss"
  },
  {
    "input": "src/global.scss"
  },
  "node_modules/leaflet/dist/leaflet.css"
],
...
```

If i resize the browser then the map is displaying properly.

**Comment by Jeremy38100** [comment]
Temporary fixed with a force window resize event.

```
ngOnInit(): void {
  window.dispatchEvent(new Event('resize'));
}
```

**Comment by reblace** [comment]
It looks like you're using a layout plugin for tabs (bootstrap?).

You need to register a handler on the tab change or tab show event and make a call to `map.invalidateSize()` as is mentioned here: https://github.com/Asymmetrik/ngx-leaflet#getting-a-reference-to-the-map

Leaflet doesn't automatically monitor DIV resize events (that would require additional javascript). The ngx-leaflet plugin monitors window resize events, which is why your workaround works. So, this is the expected behavior.

If you need more assistance, please use the ngx-leaflet tag on Stack Overflow. Thanks!
