### ISSUE TITLE
Error Adding a layer from plugin

### ISSUE THREAD

**Issue by dolpsdw** [bluehalo/ngx-leaflet#237]
I think this is an issue:
I am using ionic angular and consuming a JS plugin from 'leaflet-ant-path'
After creating the new animated layer, and assign it to the [leaftletLayer] it crash the JS
Check this commit for Crash https://github.com/dolpsdw/IonicAngularNgx-leaflet/commit/1fdd7383b3c16f80f0b556ba3d0131b21227a373
![image](https://user-images.githubusercontent.com/4348598/65537230-262fad00-df05-11e9-9f22-9d1930251f9f.png)

But if i add it directly to the map reference it runs ok.
Check this commit for Layer being added.
https://github.com/dolpsdw/IonicAngularNgx-leaflet/commit/a09adbf0d67977ab2d12b8c38faadd28ee9b6df7

(For run the repo just do ionic serve --open)

Using latest version of everithing
    "@asymmetrik/ngx-leaflet": "^6.0.1",
    "leaflet": "^1.5.1",
    "@angular/core": "~8.1.2",
    "@ionic/angular": "^4.7.1",

Any Advices are welcomed
Thanks

**Comment by reblace** [comment]
I ran your example code (thanks for the reference to your repo :)...

It looks like the issue is that you're passing an array of layers to the [layer] input binding, which expects a single layer. You could either use the [layers] input binding, or iterate in your template and bind each layer in the array to its own div. If you're expecting the object to be a single layer (rather than an array), you might just need to check your logic that connects the output from the animated layer plugin to the ngx-leaflet plugin.

You can confirm this by putting a breakpoint in 'leaflet-layer.directive.js' on line 48 when you switch to the middle tab in your application.

**Comment by dolpsdw** [comment]
Hi, thanks for taking time to analize it.

> you're passing an array of layers

True, ant path return 1 svg layer for solid line and 1 svg for animated lines.

> you're passing an array of layers to the [layer] input binding
You could use the [layers]

Solved then, not an issue, thanks for the point 👍 
`[leafletLayers]="layers"` instead of `[leafletLayer]="layers"` works !
