### ISSUE TITLE
Info on resolving the marker issue for using Angular-CLI.

### ISSUE THREAD

**Issue by BBaysinger** [bluehalo/ngx-leaflet#24]
I'm not sure how different it would be to resolve the marker issue with Angular-CLI, as it uses Webpack, but doesn't have the same configuration. Have you tried this with Angular-CLI?

**Comment by reblace** [comment]
The key is to use a custom marker by programmatically providing your own marker image (which could just be a reference to the one provided by Leaflet).

The example in the README and the example Angular2 Demo app show you how to do this directly with Webpack. Since Angular CLI uses Webpack, it would be similar, you just need to get the image to be exposed in your asset pipeline (ie. exposed by the server at a resolvable URL).

Step 1 in the README mentions importing the images you want to use. By importing the files, it will cause Webpack to process the image files and expose them as part of the webapp (either using a file loader or a url loader). As part of the build, it either generates static files that are exposed to the client (in something like a ./public directory or something) or it will serve the files out of memory. If it's the former, you should be able to find the image file names and reference those in your custom marker code. If it's the latter, you can probably get Angular CLI to output the served filenames as part of the build. In the Step 4 of the README, it shows how I reference the generated files (which the asset pipeline generates using a file hash to support caching). Since these images aren't going to change much if at all, it's not a big deal to reference the hash filename like this.

I don't personally use Angular CLI, so I'm not sure about the specifics beyond that. Hope this helps!
