### ISSUE TITLE
Marker click event 

### ISSUE THREAD

**Issue by accidentul** [bluehalo/ngx-leaflet#257]
Can. i bind a click event on the marker ?

**Comment by 4gray** [comment]
Sure, like this: 
```js
const alicanteMarker = marker([38.34517, -0.48149]).on('click', event => {
    console.log('Yay, my marker was clicked!', event);
});
```

**Comment by reblace** [comment]
Closing because an answer was provided.

The library doesn't currently provide Angular bindings for layer click events. But, as @4gray points out, it's easy to manually add them yourself. You can refer to the README to see how to make sure code you execute inside of manually registered callbacks will be run inside the Angular zone.
