### ISSUE TITLE
adding a function to map.on() event and later removing that event triggering the function without removing the event

### ISSUE THREAD

**Issue by pungiish** [bluehalo/ngx-leaflet#260]
Hey, I am providing a function to 
```
someFunc() {
this.map.on('moveend', screenShot.bind(this));
}


screenShot() {
setTimeout(this.screenShot2.bind(this), 4000);
}

screenShot2() {
// some logic
this.map.off('moveend', this.screenshot)
}
```
Now, i know that this code sucks, but I needed a weird hack and now i can't remove the moveend event only for the screenshot function. If i use this.map.off('moveend'), the map stops working correctly, obviously. Any ideas?

**Comment by pungiish** [comment]
Fixed the issue by using this.map.once inside the loop where i loop through coordinates before setting the view. However I'm still not sure how to remove the event bound to a function 😅

**Comment by reblace** [comment]
This is my guess as to what's going on.

You have two calls:
`this.map.on('moveend', screenShot.bind(this));`
and
`this.map.off('moveend', this.screenShot);

In the call to `on()`, `screenShot.bind(this)` returns a reference to an anonymous function that wraps the call to `screenShot` with the appropriate `this` context.

In the call to `off()`, `this.screenShot` is a reference to the `screenShot` function.

These two function references are pointing to different function (an anonymous function and `screenShot`). That's why the call to `off()` isn't working.

You should use a variable to store the reference to `screenShot.bind(this)` and then you can pass the variable into both the call to `on` and the call to `off`.

**Comment by pungiish** [comment]
@reblace Oh, I see. Thank you, didn't even think of that..
