### ISSUE TITLE
Partially Visible Map

### ISSUE THREAD

**Issue by kt215** [bluehalo/ngx-leaflet#267]
The main leaflet frame resizes correctly, but inside, most of the frame is gray and only about 20% on the top shows the actual map. Interestingly, the issue was not reproducible in development env, only when using deployed artifacts (ng build ...) It also works sometimes, so it looks like a race-condition.

angular 9.1.0
ngx-leaflet 7.0.0
ngx-leaflet-markercluster 3.0.0

As mentioned in https://github.com/Asymmetrik/ngx-leaflet/issues/256 the following code is a work-around:

```html
(leafletMapReady)="onMapReady($event)"
```

```js
onMapReady(map: Map) {
  setTimeout(() => {  
    map.invalidateSize();
  }, 1);
}
```

**Comment by reblace** [comment]
This is pretty common when you are using layout framework that uses javascript to manipulate the DOM after the page is rendered (e.g., tabs/accordions in Bootstrap, or resizable panels). The leaflet library only monitors window resize events as a trigger to call invalidateSize because that's the only "standard" event that can cause the page to change layout.

You should investigate that framework to see if there are draw and layout events you can hook into to add the call to map.invalidateSize().

**Comment by j-be** [comment]
@reblace I just stumble over this issue, and it seems to be a bit more intricate than that.

`ngx-leaflet` / `leaflet` (not sure which one) also seems to have problems when using something like `height: 100%` - regardless of whether the actual size changes or not. Additionally this seems to only happen if Angular is in `production` setting and I was only able to reproduce it on local network or `localhost`, but at least there it is reproducible after max. 10 reloads. The map then looks like this (notice the grey bar on the very bottom):

![image](https://user-images.githubusercontent.com/8503582/166112201-292b6d60-18fc-4736-8693-543ec6c1ee98.png)

I put together a minimal reproducer at https://github.com/j-be/ngx-leaflet-267 which is also deployed to `gh-pages`, but - as mentioned: I'm not able to reproduce it from there.

I tested using Firefox 99.0.1 and Chrome 101.0.4951.41 - both behave essentially the same.
