### ISSUE TITLE
Leaflet.js (ngx-leaflet) map tiles are not loaded properly in popup in Angular 8

### ISSUE THREAD

**Issue by mandar-raskar** [bluehalo/ngx-leaflet#268]
I'm using ngx-leaflet with angular 8 to show the map on the popup, but when I open the popup on map tiles are not overlay properly. I also used map.invalidateSize(). But still, it's not working.
![Selection_010](https://user-images.githubusercontent.com/30428372/83104657-d0845380-a0d6-11ea-95ec-dec37c611621.png)

.html code to show the popup.
`<div class="modal fade" id="collision1" role="dialog" aria-labelledby="toolenforces" aria-hidden="true">
    <div class="modal-dialog" role="document">
               <div class="row">
                 <div class="col-md-6" style="margin-top: 15px; margin-bottom: 15px;"> 
                    <div class="map1 records-map1" leaflet  [leafletOptions]="options4"
                   (leafletMapReady)="openCollision($event)"></div>
                 </div>
      </div>`

.ts code

     `     options4 = {
           layers: [
            tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png', {
             attribution: '&copy; OpenStreetMap contributors'
             })
            ],
           zoom: 7,
           center: latLng([14.1111, 121.21111])};  

           openCollision(map : L.Map){
           setTimeout(function() {
             map.invalidateSize();
            }, 10);}`

**Comment by reblace** [comment]
You want to put your call to invalidateSize inside an event that fires when the modal is shown (as opposed to when the map is loaded).

The map is probably being loaded earlier than you think it is because a lot of these libraries for models will actually add the modal HTML to the DOM but leave it hidden until it "pops up". Look to see if your modal library provides an event that fires when the modal is shown and put a call to invalidateSize in there.

**Comment by azizkhani** [comment]
I have same problem . How can i resolve this issue?
