### ISSUE TITLE
Trying to integrate angular2-leaflet into existing application

### ISSUE THREAD

**Issue by atlantageek** [bluehalo/ngx-leaflet#27]
Hi, I've built an application using ng-cli
Ive followed the directions on the README and am trying to drop your demo module into my existing app
Im getting the following error:
ERROR in [default] /<snip>/trunk/node_modules/@asymmetrik/angular2-leaflet/dist/leaflet/core/leaflet.directive.d.ts:1:0
Cannot find type definition file for 'leaflet'.

Any suggestions.

**Comment by reblace** [comment]
If you are working in typescript, you'll need to install the npm module ```@types/leaflet``` to get the leaflet typings definition. You can use the example demo as a reference.

There was a breaking change in the latest patch version of the @types/leaflet typings file, but if you grab the latest @asymmetrik/angular2-leaflet it should work. Let me know if you have any issues.

**Comment by atlantageek** [comment]
Thanks. good call on updating from master. I was hitting an issue and  didnt realize it. I checked out master and it worked .
There were several leaflet angular 2 directories out there and I chose yours because it was most active.  Do you feel it is getting close to production ready?

**Comment by reblace** [comment]
Thanks for the feedback!

My organization uses this component in several production systems, so it will likely stay active and up-to-date with the latest Angular2 and Leaflet. We created it because when we first started working with Angular2 there wasn't a good, active leaflet component that was easily extensible.

This component is relatively easy to extend (you can see how the core directive is extended by the layers directive or check out the angular2-leaflet-draw component to see how the extension works). The reason was so we could keep the core component relatively simple and add functionality as needed.

We're trying to stay true to semver, but we did recently make changes to how we were bundling/exporting the component which introduced some potential instability due to how we were building/transpiling/bundling the typescript.

Also, generally, we use Webpack directly to bundle our angular apps (as opposed to the Angular CLI) and we write them in Typescript. So, that support should stay consistent.

With respect to your specific issue, we don't list typings as peer dependencies because whether you need the typings or not is dependent on how you are using the library (Typescript vs not). We should update the README with a reference to them though. The breaking change in the leaflet typings was a surprise. That's all managed by DefiniatelyTyped. I'm not sure how that happened because usually they are very strict about that sort of thing. But, looking at the recent commit history, a bunch of changes were made to the leaflet typings over the last couple weeks. We encountered the same issue internally and had to do some minor refactoring of the component and our systems to address the change.

**Comment by reblace** [comment]
Closing as I think the question was answered. Thanks!
