### ISSUE TITLE
Using leaflet.markercluster

### ISSUE THREAD

**Issue by jessenic** [bluehalo/ngx-leaflet#39]
I have tried to use leaflet.markercluster with angular2-leaflet and @angular/cli.

I have tried this:
```
import * as L from 'leaflet';

import 'leaflet.markercluster';
```
but using any of the markercluster extensions produce a "ng build" compile error saying they are not found on type "typeof L". Any suggestions?

**Comment by reblace** [comment]
The specific issue you're having is that the typings for leaflet.markercluster are not being found.

Make sure you're installing them:
https://www.npmjs.com/package/@types/leaflet-markercluster

```
npm install @types/leaflet-markercluster
```

**Comment by reblace** [comment]
Also, just FYI - we have a need for a plugin like this one, so I might add a package for it soon.

**Comment by andreafedele** [comment]
I'm facing the same problem, and it seems that the typings don't resolve it. 
What else could it be?
Thank you.

**Comment by reblace** [comment]
You can try this out: https://github.com/Asymmetrik/angular2-leaflet-markercluster - It's a WIP. 

Do you have some sample code that reproduces the issue?

**Comment by reblace** [comment]
There are a couple of ways to address this in the ng cli project.

1. Add an explicit reference to the types definition file to the top of the file that is doing the work with the leaflet marker cluster types:

```
/// <reference path="../../node_modules/@types/leaflet-markercluster/index.d.ts" />
```

2. Remove the types array from the ```src/tsconfig.app.json``` file:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": ""
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

I would have to assume the issue is related to the fact that the name of the @types bundle is different from the name of the actual package. It seems specific to ng cli cause I have my own webpack build that I use in other projects and I didn't run into this issue. However, either of the above solutions worked for me in a new ng cli project that includes @asymmetrik/angular2-leaflet and then manually integrates the marker cluster plugin.

A couple other notes about what you're trying to do:

1. You're likely going to need to apply the marker image fix referenced in the README.
2. You will need to include the ```../node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css``` file in your ```.angular-cli.json``` file for the clusters to be styled correctly.

**Comment by reblace** [comment]
Going to close this as answered unless you have any other issues related to the plugin. Thanks for the feedback!

**Comment by severinbeauvais** [comment]
I'm using
```
"leaflet": "^1.3.1",
"leaflet.markercluster": "^1.3.0"
```
and
```
"@types/leaflet": "^1.2.6",
"@types/leaflet-markercluster": "^1.0.3"
```
The following worked for me:
```
import 'leaflet';
import 'leaflet.markercluster';

const L = window['L'];
```
