### ISSUE TITLE
How to access the map instance ?

### ISSUE THREAD

**Issue by maisnamraju** [bluehalo/ngx-leaflet#43]
I want to get coordinates from the map based on the mouse position. I don't see a way  to do this in the docs, is there a way I could achieve this ?

**Comment by reblace** [comment]
There's an output/event emitter that is exposed as ```leafletMapReady```. The object in the event is a reference to the Map:

```js
@Output('leafletMapReady') mapReady = new EventEmitter<L.Map>();
```

Alternatively, if you are extending the directive with your own leaflet functionality, you can inject the directive into your own using DI:

```js
constructor(leafletDirective: LeafletDirective) { ... }
```

Then, the map is available via ```getMap()```

**Comment by maisnamraju** [comment]
Thanks, I was after to get it after looking at the leaflet draw component but this should have been inside the documentation I guess.

**Comment by reblace** [comment]
Yeah, it's missing from the docs. I'll update the README when I get a chance. Thanks for the feedback!

**Comment by maisnamraju** [comment]
Hi, I'm still stuck with an issue and can't see to figure it out, would appreciate some help. 

```

export class AddLocationComponent implements OnInit {
    public options: Object;
    public locations: Array<T> = [];
    public leafletDirective: LeafletDirectiveWrapper;
    private subscriptions: Array<Subscription> = [];

    constructor(leafletDirective: LeafletDirective) {
      this.leafletDirective = new LeafletDirectiveWrapper(leafletDirective);
    }

    public ngOnInit() {
        // will bring coordinates from team details
        this.options = {
            zoom: 10,
            center: L.latLng([46.879966, -121.726909]),
            attributionControl:false,
            layers: [L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 25 })]
        };

        this.leafletDirective.init();

        this.leafletDirective.getMap().on('click', () => {
           console.log(e);
         });

    }

}
```

I'm trying to get the the lat-lang coordinates on the map based on a mouse click, am I missing? 

```
Error: Uncaught (in promise): TypeError: Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
    at AddLocationComponent.ngOnInit 
... 
```
I based my code on the drawer plugin.

**Comment by reblace** [comment]
If you want to inject the directive like that, you'll need to make sure that your customer component is on the same DOM element as the leaflet directive, and that it is declared after the leaflet directive. Eg:

```js
<div leaflet
        myCustomComponent>
</div>
```
If you do that, the injected leaflet directive instance should be the one you want. What's probably happening is there's no instance of the LeafletDirective available to be injected due to the way the scoping works.


An alternative approach could be to use ```@ViewChild``` in your component:
```
@ViewChild(LeafletDirective)
leafletDirective: LeafletDirective;
```
With @ViewChild, I think the directive needs to be on a child DOM element of the component.


Or, you can use the ```@Output``` leafletMapReady binding:
```html
<div leaflet leafletFilter (leafletMapReady)="onMapReady($event)"></div>
```
```js
onMapReady(map: L.Map) {
	this.map = map;
	this.mapReady.emit(this.map);
}
```

If you're writing an extending directive, I'd inject the LeafletDirective. If the map might change or show/hide, I'd consider using the @ViewChild approach. Otherwise, stick with a handler registered to the leafletMapReady output event emitter.

**Comment by maisnamraju** [comment]
You are a hero. Thanks a lot; I used the event emmiter approach on the component itself and was able to get the coordinates.
