### ISSUE TITLE
Marker and HTML

### ISSUE THREAD

**Issue by chujzaurus** [bluehalo/ngx-leaflet#58]
Hello,

I have a question: 
Is it possible to access marker HTML or apply CSS classes to a marker? I want to be sure, before I would rewrite all my gmaps code to leaflet. Thanks!

**Comment by reblace** [comment]
Yeah, this is more of a question for the Leaflet library itself, but you can create markers and pass in custom markers that are Divs rather than images. See the docs for: http://leafletjs.com/reference-1.0.0.html#divicon

You would add them as layers to the map using the layers input binding just like any other layer.
