### ISSUE TITLE
click inside marker popup

### ISSUE THREAD

**Issue by scne** [bluehalo/ngx-leaflet#60]
I build my popup text for single marker through a loop. I need to bind click event for each line of my popup text to a function and I've coded something like this lines

```
uris = uris.concat('<a (click)="showSelected("' + uri.s.value + '")" href="#" >' + uri.s.value + '</a><br>'); 
 L.marker([long, lat], {
                  icon: L.icon({ iconUrl: 'assets/marker-icon.png', shadowUrl: 'assets/marker-shadow.png' })
                }).bindPopup(uris).addTo(this.map);
```
but  `showSelected` isn't call in any way. Can I perform this or I need to change my logic?

**Comment by reblace** [comment]
This is an Angular question. Your (click) output bindings aren't going to be compiled by Angular because they don't exist until runtime. You'll have to go research how to generate a dynamic template with bindings in Angular. You can probably get the event handlers working independently of Angular and then bridge the gap to your component in code. But, I'm not sure how the scope of the html handler is resolved.

When I've done this in the past, I've had a generic template as part of the component that includes the map. Then, I manually register a callback on the click event for the marker and manually show and reposition the template so that it's drawn where the tooltip should be drawn. This way, the template itself stays in the Angular ecosystem.

I'm gonna close this since the solution isn't really related to the angular2 leaflet plugin. Thanks for using the plugin!

**Comment by M00ker** [comment]
@scne Did you get this working?  I need to do the same thing and would like to know your solution.

Thanks

**Comment by olivierto** [comment]
+ 1 do you have any clue on how we can get this to work?

**Comment by MrRandomInternetDude** [comment]
I'm now the third person who would like to see how this works. :]

**Comment by KununguaK-Iversen** [comment]
4th

**Comment by soromamadou** [comment]
5th.
Sure this is note related to the plugin. But it shoud be useful to know how we can achive that.
With Agm it is easy as the popup can be set in the html file. I don't know how to achieve this with leaflet plugin. So due to only this problem i have to use Agm instead of your plugin
Any help will be welcome.
Thanks

**Comment by soromamadou** [comment]
Hi,
i got something.
When i set an host listener in the component, i can get the event:

`
    @HostListener('document:click', ['$event'])
    clickout(event) {
        console.log(event.target.getAttribute("data-type"));
        if(event.target.classList.contains("my-great-class")){
            this.alertNew();
        }
    }`

like this i can get the element in the popup with class "my-great-class" and call alertNew function from my component.
Also i can get extra data from the popup like "data-type".

Hope it help someone

**Comment by Rosscotini** [comment]
@soromamadou Very nice solution!
