### ISSUE TITLE
Lack of documentation for markers section

### ISSUE THREAD

**Issue by probadb** [bluehalo/ngx-leaflet#64]
Hi,

It's unclear in the current version of the package and README how to add a marker to the map.

You state

> 4. Configure Leaflet to use the correct URLs as customer marker images
> ```
> let layer= L.marker([ 46.879966, -121.726909 ], {
>  	icon: L.icon({
>  		iconSize: [ 25, 41 ],
>  		iconAnchor: [ 13, 0 ],
>  		iconUrl: '2273e3d8ad9264b7daa5bdbf8e6b47f8.png',
>  		shadowUrl: '44a526eed258222515aa21eaffd14a96.png'
>  	})
>  });
> ```

but where do i add this `layer` in the directive parameters?

I tryed everything, but nothing works, and I went in the demo forlder but the example of marker is too much complicated for a starting point.

Leaflet way was to do something like `L.marker([50.5, 30.5]).addTo(map);` and it's added.

Can you please clarify this in the documentation or make an example with marker, popup and tooltip as they are widely used around?

Thank you

**Comment by probadb** [comment]
I just found what is to be done for markers:

```
  layers: L.Layer[] = [];

  marker = L.marker([44.0, 11.0], {
    icon: L.icon({
      iconSize: [48, 48],
      iconAnchor: [24, 48],
      iconUrl: '/assets/images/marker.svg'
    })
  });

// [...] this is an example to just add markers later onInit

  ngOnInit() {
    this.layers.push(this.marker);
  }

```

but if you do it later it will not add any marker: eg. 
```
let self= this;
setTimeout(function(){ self.layers.push(this.marker); }, 2000)
```

but the native leaflet allow this:
```
    let self = this;
    setTimeout(function(){ self.marker.addTo(map); }, 2000)
```

**Comment by reblace** [comment]
Yeah, this was something I struggled with recently.

First, you would to add it to the layers you are binding to the map using the input bindings.

Second, the issue you're seeing with markers not getting picked up has to do with how Angular does change detection. For performance reasons, they want you to treat objects as being immutable. Basically, try to avoid using ```Array.push(obj)``` and instead do something like ```this.layers = this.layers.concat([obj]);```.

This isn't really an issue if you're pushing on to an array in the ngOnInit function as that all happens before change detection starts, but your changes won't be detected later in the lifecycle if you mutate the arrays. 

I need to add some details to the README about this.

**Comment by probadb** [comment]
well but the normal behaviour of the leaflet is you can add markers whenever you want in the future and they will just show up in the map `self.marker.addTo(map)`
Also angular would update a table, a list, ... if the array is changed  sometimes in the future. So I expected it to work in angular way (as currenty it works in default leaflet.addTo(map)).
If the layers need to be immutable then there should be another way to do it instead of having to bind to a workaround I used like this:
```
  onMapReady(map: L.Map) {
    let self = this;
    setTimeout(function(){ self.marker.addTo(map); }, 2000)
  }
```

I used this approach to bind a ngDoCheck and add markers...

**Comment by reblace** [comment]
Everything you're saying is correct, but the implementation decisions are a little complicated. Here's a complete explanation:

Geeky explanation (you prob know all of this already, but I'm putting the full explanation for anyone else who has this issue):

The plugin allows you to input bind an array to track layers. The plugin is using ngOnChanges to track changes to the array. When you use ngOnChanges, Angular is using the default change detection strategy, which is an instance equality differ.

Instance equality differs will only detect changes if the actual instance of the array changes. This default strategy works great most of the time because most template binding is done on primitives, which are immutable. But, arrays are tricky cause they are mutable.

ngFor overrides the default change detection strategy by using an iterable differ. The iterable differ will detect changes to the contents of the array. This is why ngFor will update a table or list or whatever.

The consequence of using an iterable differ is that you always have to compare the array states in order to tell if anything has changed. If you have a large array, this can be very expensive. ngDoCheck gets called a LOT.

In Leaflet, you might have a lot of markers you want to add to the map (hundreds/thousands?). When this is the case, every time ngDoCheck is called, you're doing a content comparison between the two arrays and that might negatively impact performance. This is part of why ngFor can get slow for really large arrays.

I have a new (unreleased) branch of this plugin that uses custom differs and ngDoCheck to allow mutations on the layers array (and I also use a key-value differ to detect changes on the layers control object). I haven't had a chance to test to determine the performance impact in different use cases before I release it. Until then, you have to treat the bound arrays as if they are immutable for the plugin to pick up and apply the changes properly. It's a bit of a pain, but also a pretty minor change.

In JS (particularly V8 engine), array operations are extremely optimized. Concatenating to add to an array rather than pushing shouldn't have a huge impact to performance.

There are a couple options I'm exploring:

1. Allow array mutation. Use iterable differ and ngDoCheck to detect the changes without requiring an instance change. Suggest that people keep the layers array small - O(10) - and if they need to add a lot of layers or markers, add them to a group layer instead of directly to the layer array.

2. Force immutable array operations for change detection to work. Use ngOnChanges to detect changes using default instance equality differ. Suggest people use concat or slice to create a new array instance when changes are made (which is unintuitive).

In your specific case, you should be able to add your markers to the array after ngOnInit. But, you'd need to do something like this:

```js
layers.push(marker);
layers = layers.slice();
```

or

```js
layers = layers.concat([marker]);
```

If you do one of the above, your markers should get added to or removed from the map via the plugin.

**Comment by reblace** [comment]
I released a new version of the plugin that supports mutable changes.
I also added some documentation on how to add markers to the map. Check it out and let me know if you have any other issues. Thanks!
