### ISSUE TITLE
Cannot find module '@asymmetrik/ngx-leaflet.module'

### ISSUE THREAD

**Issue by majid701** [bluehalo/ngx-leaflet#71]
I have an Angular 4+ project setted up with angular cli. I installed the modules with yarn but importing `'@asymmetrik/ngx-leaflet.module` in my app.module is not working.

I see that the name of the module has been changed recently, maybe something is wrong there?

**Comment by lironta** [comment]
I have the same problem too... what can i do?
EDIT:
try this:
import { LeafletModule } from '../../node_modules/@asymmetrik/ngx-leaflet';

**Comment by majid701** [comment]
@lironta 
I just figured out you don't need to specify the whole node_modules path. 
This works: `import { LeafletModule } from '@asymmetrik/ngx-leaflet'`

The documentation needs to be updated.

**Comment by reblace** [comment]
Can you clarify what the issue was and what the resolution was? Or if you are still having issues?

The typescript import should not typically reference the node_modules path (unless you have a weird custom ts config).

I'm using the new renamed module successfully in an ng cli project.

If there's an issue with the documentation, can you provide the specific issue? Thanks!

**Comment by majid701** [comment]
@reblace the problem is in the README file at line `121`
this line exactly `import { LeafletModule } from '@asymmetrik/ngx-leaflet.module';`

It does'nt work like that but it works by removing `.module`.

So the README needs to be updated to:
`import { LeafletModule } from '@asymmetrik/ngx-leaflet';`

**Comment by reblace** [comment]
Ahhhh. I see, yeah I know exactly how that typo ended up in there. I'll fix is ASAP. Thanks!

**Comment by reblace** [comment]
Fixed the README. Sorry for the confusion!
