### ISSUE TITLE
Angular 4 Leaflet rendering issue

### ISSUE THREAD

**Issue by Boud** [bluehalo/ngx-leaflet#97]
When the page loads the leaflet map is not properly loaded, most of it is grey only a small part is rendering properly. If the window is resized (showing the chrome debug tools for example), the leaflet map is then rendered properly and works like a charm.

![bugleaflet](https://user-images.githubusercontent.com/3704952/32727869-803c728c-c87e-11e7-8943-9431d31637da.png)

I have tried to call `map.invalidateSize();` (since this is what leaflet seems to call when resized) and even `map.setView()` in a desperate attempt but none of it worked. I was calling them after the map initializes in the ngAfterViewInit

Did you encounter a similar problem or know how to solve this ?

Thanks in advance and thank you for the great plugin !

**Comment by reblace** [comment]
Can you post your component and template? Almost always, this is due to the dom changing (resize or show/hide) without calling invalidateSize(). If you can provide your code I can look into whether its related to anything in the plugin.

The most common cause of this issue is if you're using some kind of JS dom resize operation or you are using show/hide on the dom element.

Fwiw, we're experiencing this right now with Wordpress, but suspect it's just some DOM layout manipulation we aren't handling.

**Comment by Boud** [comment]
Thank you for your response

I suspected that was happening and my first instinct was to blame the ng-if but it wasn't what was causing the issue.

I managed to bypass the problem by calling invalidateSize() later in the "lifecycle" with `ngAfterViewCheck` instead of `ngAfterViewInit` and now the leaflet map is working correctly on load.

Not sure it's the best way to do it since I couldn't pinpoint the real source of the problem but It'll do for now !

Thanks again, I'm closing the issue :)

**Comment by mcurtis22** [comment]
Hey Boud, I was working on this issue in WordPress. As you mentioned, a "fix" is possible by calling `invalidateSize()` in `ngAfterViewCheck`, but do note that that lifecycle method gets called every change detection cycle. We were able to pinpoint our issue to a workaround that hid the body with a `display: none` until all JS was loaded and then set the body's CSS to `display: block`. Our fix was using the visibility rule instead of the display rule.

If you'd like to reopen this issue and provide more details about your HTML, maybe we can come up with a better solution.

**Comment by fjorquerauribe** [comment]
Hi, what are your dependencies?
I've got this error
![error](https://user-images.githubusercontent.com/14946707/34969027-7c6ae6ee-fa4b-11e7-9df3-cc891ee10f62.png)

**Comment by reblace** [comment]
3.x depends on Angular 5.
2.x depends on Angular 4.

The error you're seeing is most likely that you're using @asymmetrik/ngx-leaflet 3.x with Angular 4.
